name: Deploy client to S3 and on merge

on:
  push:
    branches:
      - develop
    paths:
      - 'client/*'

jobs:
  build_and_deploy_to_s3:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'client'
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          npm install
          npm run build

      - name: Deploy to S3
        uses: reggionick/s3-deploy@v4
        with:
          folder: dist
          bucket: ${{ secrets.S3_BUCKET  }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION  }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID  }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
