name: Deploy client to S3 and on merge

on:
  push:
    branches:
      - develop
    paths:
      - 'client/**/*'

jobs:
  build_and_deploy_to_s3:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'client'
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build client for production
        env:
          VITE_VITE_BACKEND_HOST: ${{ secrets.VITE_BACKEND_HOST }}
          VITE_MAPS_API: ${{ secrets.VITE_MAPS_API }}
          VITE_UNSPLASH_ACCESS_KEY: ${{ secrets.VITE_UNSPLASH_ACCESS_KEY }}
        run: npm run build

      - name: Deploy to S3
        uses: reggionick/s3-deploy@v4
        with:
          folder: client/dist
          bucket: ${{ secrets.S3_BUCKET  }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION  }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID  }}
          invalidation: /
          delete-removed: true
          private: true
